### ISSUE TITLE
Warning: Prop `style` did not match. Server: "left:0;color:#ffbc0b;width:2%" Client: "left:0;color:#ffbc0b;transition:;width:2%"  in nextjs 13

### ISSUE THREAD

**Issue by Shani-Sinojiya** [awran5/react-simple-star-rating#40]
![image](https://user-images.githubusercontent.com/72117665/217830428-925c536b-3320-4097-819b-056b6366d67d.png)

**Warning: Prop `style` did not match. Server: "left:0;color:#ffbc0b;width:2%" Client: "left:0;color:#ffbc0b;transition:;width:2%"**

**Comment by titi60** [comment]
add transition={true} to Rating component

**Comment by RishikeshDarandale** [comment]
When `readonly={true}`, then following error occurs:

```
client.js:1 Warning: Prop `style` did not match. Server: "null" Client: "cursor:"
    at span
    at span
    at exports.Rating (webpack-internal:///./node_modules/react-simple-star-rating/dist/index.js:1:2743)
```

**Comment by RishikeshDarandale** [comment]
> When `readonly={true}`, then following error occurs:
> 
> ```
> client.js:1 Warning: Prop `style` did not match. Server: "null" Client: "cursor:"
>     at span
>     at span
>     at exports.Rating (webpack-internal:///./node_modules/react-simple-star-rating/dist/index.js:1:2743)
> ```

This can be resolved with following props

```
style={{
          cursor: readonly ? 'default' : 'pointer',
        }}
```
